In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv('./dados_conjuntos.csv')

In [3]:
padrao = r"""[^\w\s\.\-_:\/áéíóúâêîôûàèìòùãõçÁÉÍÓÚÂÊÎÔÛÀÈÌÒÙÃÕÇ]"""

In [4]:
def limpar_coluna(df, nome_coluna):
    """
    Remove caracteres especiais da coluna especificada de um DataFrame,
    preservando letras acentuadas, números, espaços e os seguintes sinais de pontuação:
    hífen (-), underscore (_), ponto (.), dois pontos (:) e barra (/)
    
    Parâmetros:
    - df: pandas.DataFrame
    - nome_coluna: str
    
    Retorna:
    - DataFrame com a coluna limpa
    """
    
    def limpar_texto(texto):
        texto = str(texto)
        texto = re.sub(r'[\t\n\r\f\v]', ' ', texto)        # substitui tabulações e quebras de linha por espaço
        texto = re.sub(padrao, '', texto)                  # remove caracteres indesejados
        texto = re.sub(r'\s+', ' ', texto).strip()         # remove múltiplos espaços e espaços nas bordas
        return texto
    
    df[nome_coluna] = df[nome_coluna].apply(limpar_texto)
    return df

In [5]:
df = limpar_coluna(df, 'nomeRecurso')

In [6]:
df

,id,titulo,periodicidade,visibilidade,descontinuado,link,formato,tamanho,nomeRecurso,dataCadatroRecurso,lastUpdateRecurso,dataUltimaAtualizacaoMetadados,dataUltimaAtualizacaoArquivo,atualizado
0,3fc794a6-4217-4038-9b9d-b0ac7335efc3,"""Patrimônio Genético Nacional"" que foram envol...",NaN,PUBLICA,False,https://dadosabertos.ufam.edu.br/dataset/3fc79...,XLSX,9505.0,Patrimônio Genético Nacional que foram envolvi...,07/02/2025,07/02/2025,07/02/2025 19:59:50,07/02/2025 19:59:50,Atualização não verificável
1,6162d5bd-e6d8-4a2e-b4d7-339356c2b167,01. Comissões Institucionais Permanentes,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,CSV,0.0,01. Comissões Institucionais Permanentes,29/01/2024,22/01/2024,31/01/2024 17:56:40,22/01/2025 18:08:47,Atualizado
2,6162d5bd-e6d8-4a2e-b4d7-339356c2b167,01. Comissões Institucionais Permanentes,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,PDF,0.0,01. Comissões Institucionais Permanentes,29/01/2024,22/01/2024,31/01/2024 17:56:40,22/01/2025 18:08:47,Atualizado
3,6162d5bd-e6d8-4a2e-b4d7-339356c2b167,01. Comissões Institucionais Permanentes,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,PDF,0.0,01. Comissões Institucionais Permanentes,30/01/2025,22/01/2025,31/01/2024 17:56:40,22/01/2025 18:08:47,Atualizado
4,6162d5bd-e6d8-4a2e-b4d7-339356c2b167,01. Comissões Institucionais Permanentes,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,CSV,0.0,01. Comissões Institucionais Permanentes,30/01/2025,22/01/2025,31/01/2024 17:56:40,22/01/2025 18:08:47,Atualizado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68659,00b8e0e8-2ed2-4896-8c62-91ef2cc5193c,SFN - SICOOB CONEXÃO,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v2,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 16:47:09,Indisponível,Atualização não verificável
68660,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,HTML,0.0,API - Documentação do DASFN Catálogo de Dados ...,24/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável
68661,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,API,0.0,API - Navegador do DASFN Catálogo de Dados Abe...,16/08/2024,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável
68662,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v1,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável
68663,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v2,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável

In [7]:
# selecionar apenas dados com periodicidade e com formatos de recuros validos
df = df[(df.formato.str.contains(r'csv|cvs|xls|zip|json|xml|rar|html', case=False, na=True))]
# df = df[(df.periodicidade != 'SOB_DEMANDA') & (df.periodicidade.notna()) & (df.formato.str.contains(r'csv|cvs|xls|zip|json|xml|rar|html', case=False, na=True))]

In [8]:
df

,id,titulo,periodicidade,visibilidade,descontinuado,link,formato,tamanho,nomeRecurso,dataCadatroRecurso,lastUpdateRecurso,dataUltimaAtualizacaoMetadados,dataUltimaAtualizacaoArquivo,atualizado
0,3fc794a6-4217-4038-9b9d-b0ac7335efc3,"""Patrimônio Genético Nacional"" que foram envol...",NaN,PUBLICA,False,https://dadosabertos.ufam.edu.br/dataset/3fc79...,XLSX,9505.0,Patrimônio Genético Nacional que foram envolvi...,07/02/2025,07/02/2025,07/02/2025 19:59:50,07/02/2025 19:59:50,Atualização não verificável
1,6162d5bd-e6d8-4a2e-b4d7-339356c2b167,01. Comissões Institucionais Permanentes,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,CSV,0.0,01. Comissões Institucionais Permanentes,29/01/2024,22/01/2024,31/01/2024 17:56:40,22/01/2025 18:08:47,Atualizado
4,6162d5bd-e6d8-4a2e-b4d7-339356c2b167,01. Comissões Institucionais Permanentes,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,CSV,0.0,01. Comissões Institucionais Permanentes,30/01/2025,22/01/2025,31/01/2024 17:56:40,22/01/2025 18:08:47,Atualizado
5,82aa00f1-10e6-4724-bb97-9d25f4683be2,02. Óbitos da Internação Hospitalar,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,CSV,0.0,02. Óbitos da Internação Hospitalar,29/01/2024,29/01/2024,31/01/2024 17:56:23,22/01/2025 16:35:47,Atualizado
8,82aa00f1-10e6-4724-bb97-9d25f4683be2,02. Óbitos da Internação Hospitalar,ANUAL,PUBLICA,False,https://www.gov.br/ebserh/pt-br/hospitais-univ...,CSV,0.0,02. Óbitos da Internação Hospitalar,30/01/2025,22/01/2025,31/01/2024 17:56:23,22/01/2025 16:35:47,Atualizado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68658,00b8e0e8-2ed2-4896-8c62-91ef2cc5193c,SFN - SICOOB CONEXÃO,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v1,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 16:47:09,Indisponível,Atualização não verificável
68659,00b8e0e8-2ed2-4896-8c62-91ef2cc5193c,SFN - SICOOB CONEXÃO,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v2,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 16:47:09,Indisponível,Atualização não verificável
68660,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,HTML,0.0,API - Documentação do DASFN Catálogo de Dados ...,24/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável
68662,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v1,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável
68663,5df1b920-3358-4259-99e7-1974a071665b,SFN - SICOOB COOPERMAIS,NaN,PUBLICA,False,https://olinda.bcb.gov.br/olinda/servico/DASFN...,JSON,0.0,Canais de Atendimento v2,25/07/2023,Indisponível (Cabeçalho 'Last-modified' não en...,17/08/2024 17:27:57,Indisponível,Atualização não verificável

In [9]:
df_varios_dataset = df[['id','titulo','formato']].groupby(['id','formato']).count().reset_index()
df_varios_dataset = df_varios_dataset[df_varios_dataset.titulo > 2]

In [10]:
df = df[df.id.isin(df_varios_dataset.id)]

In [11]:
# removendo linhas duplicadas
df = df[['id', 'titulo']].drop_duplicates()

In [12]:
df.to_csv('./candidatos_schema_matching_dados_gov_v2.csv', index=False)
# df.to_csv('./candidatos_schema_matching_dados_gov.csv', index=False)